Make interactive programs work

diff --git a/docker_image/run_simula b/docker_image/run_simula
--- a/docker_image/run_simula
+++ b/docker_image/run_simula
@@ -1,35 +1,15 @@
 #!/bin/bash
 
-function main {
-    # Exit on error
-    set -e
+PROGRAM_NAME="program"
 
-    # Generate random program name
-    UUID=$(cat /proc/sys/kernel/random/uuid)
-    PROGRAM_NAME=program-$UUID
+# Compile capturing errors
+cim $PROGRAM_NAME &> $PROGRAM_NAME.log
 
-    # Save stdin to file
-    cat - > $PROGRAM_NAME.sim
+if [ $? -ne 0 ]; then
+    # Failed, show compiler output and exit
+    cat $PROGRAM_NAME.log
+    exit
+fi
 
-    # Compile capturing errors
-    set +e
-    cim $PROGRAM_NAME &> $PROGRAM_NAME.log
-
-    if [ $? -ne 0 ]; then
-        # Failed, show compiler output and exit
-        cat $PROGRAM_NAME.log
-        exit
-    fi
-
-    # Run
-    ./$PROGRAM_NAME
-}
-
-function clean_up {
-    rm -f $PROGRAM_NAME*
-}
-
-# Clean up on exit
-trap clean_up EXIT
-
-main
+# Run compiled program
+./$PROGRAM_NAME
